# Generated by Django 5.1.2 on 2024-11-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_alter_watches_options_watches_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watches',
            name='time',
        ),
    ]
